
    export const Data = ([
        {id: 'gown101', categories: "Gown", name: "Gown", code: '1001AB',description: "Red/ Pink Mocklayer Solid Kurta",image: '../image/gown1.jfif',color: 'red / Pink',price: 2500 ,descriptionription: 'Orange Round Neck Printed Gown',mrp: 'Rs. 4500',price: 8900 ,febric: "cotton",sleeve: "Full Sleeve",shape: "Straight",pattern: "Printed",care: "Hand Wash",occesion: "Festival",bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000'},
         {id: 'gown102', categories: "Gown", name: "Gown", code: '1002AB', description: "Blue Mocklayer Solid Kurta", image: '../image/gown2.jfif', color: 'Yellow', descriptionription: 'Yellow Mandarin Neck Flared Gown', mrp: 'Rs. 4500', price: 8900 , febric: "cotton", sleeve: "Full Sleeve", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000' },
        {id: 'gown103', categories: "Gown", name: "Gown", code: '1003AB', description: "Pink Mocklayer Solid Kurta", image: '../image/gown3.jfif', color: 'Pink', descriptionription: 'njkjjjnhdnsgtr trty tuyu uyt ut bdjskjndjsnjhnjsbjbsa', mrp: 'Rs. 4500', price: 8900 , febric: "cotton", sleeve: "Full Sleeve", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000' },
        {id: 'gown104', categories: "Gown", name: "Gown", code: '1004AB', description: "White / Blue Mocklayer Solid Kurta", image: '../image/gown4.jfif', color: 'White & Blue', descriptionription: 'njkjjjnhdnsgtr trty tuyu uyt ut bdjskjndjsnjhnjsbjbsa', mrp: 'Rs. 4500', price: 8900 , febric: "cotton", sleeve: "Full Sleeve", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000'   },
        {id: 'gown105', categories: "Gown",name: "Gown", code: '1005AB',description: "Blue Mocklayer Solid Kurta",image: '../image/gown5.jfif',color: 'Black',descriptionription: 'njkjjjnhdnsgtr trty tuyu uyt ut bdjskjndjsnjhnjsbjbsa',mrp: 'Rs. 4500',price: 8900 ,febric: "cotton",sleeve: "Full Sleeve",shape: "Straight",pattern: "Printed",care: "Hand Wash",occesion: "Festival",bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000'},
        // {id: 'gown106', categories: "Gown", name: "Gown", code: '1006AB', description: "Pink Mocklayer Solid Kurta", image: './image/gown6.jfif', color: 'Pink', descriptionription: 'njkjjjnhdnsgtr trty tuyu uyt ut bdjskjndjsnjhnjsbjbsa', mrp: 'Rs. 4500', price: 8900 , febric: "cotton", sleeve: "Full Sleeve", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000' },
        // {id: 'gown107', categories: "Gown",name: "Gown",description: "Blue Mocklayer Solid Kurta",code: '1007AB',image: './image/gown7.jfif',color: 'Grey',descriptionription: 'njkjjjnhdnsgtr trty tuyu uyt ut bdjskjndjsnjhnjsbjbsa', mrp: 'Rs. 4500',price: 2300 ,febric: "cotton",sleeve: "Full Sleeve",shape: "Straight",pattern: "Printed",care: "Hand Wash",occesion: "Festival",bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000' },
        // {id: 'gown108',categories: "Gown", code: '1008AB', description: "Blue Mocklayer Solid Kurta", categories: "gown", name: "G", image: './image/gown8.jpg', color: 'Brown/ Coffee', descriptionription: 'njkjjjnhdnsgtr trty tuyu uyt ut bdjskjndjsnjhnjsbjbsa', mrp: 'Rs. 4500', price: 8900 , febric: "cotton", sleeve: "Full Sleeve", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000' },
       
        { id:"fullsuit101",categories: "Fullsuit",name: "Full Suit",dress: 'suit', code: '1009AB',mrp: 'Rs. 2500',price: 8900 ,febric: "cotton",sleeve: "Full Sleeve",color: "Blue",shape: "Straight",pattern: "Printed",care: "Hand Wash",occesion: "Festival",image: '../image/suit1.jpg',description: "Blue Mocklayer Solid Kurta",bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000' },
        { id:"fullsuit102",categories: "Fullsuit", name: "Full Suit", dress: 'suit',  code: '1010AB', mrp: 'Rs. 3500', price: 2300 , febric: "cotton", sleeve: "Full Sleeve", color: "Pink", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: '../image/suit2.jpg', description: "Pink Mocklayer Solid Kurta", bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000' },
        { id:"fullsuit103",categories: "Fullsuit",name: "Full Suit",dress: 'suit',  code: '1011AB', mrp: 'Rs. 4200', price: 1300 , febric: "cotton", sleeve: "Full Sleeve", color: "Orange", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: '../image/suit3.jpg', description: "Blue Mocklayer Solid Kurta", bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000'},
        { id:"fullsuit104",categories: "Fullsuit",name: "Full Suit",dress: 'suit',code: '1012AB',mrp: 'Rs. 1800',price: 3300 ,febric: "cotton",sleeve: "Full Sleeve",color: "Green", shape: "Straight", pattern: "Printed", care: "Hand Wash",occesion: "Festival",image: '../image/suit4.jpg',description: "Green Mocklayer Solid Kurta",bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000' },
        { id:"fullsuit105",categories: "Fullsuit",name: "Full Suit",dress: 'suit',code: '1013AB',mrp: 'Rs. 3500',price: 4500 ,febric: "cotton",sleeve: "Full Sleeve",color: "Red",shape: "Straight",pattern: "Printed",care: "Hand Wash",occesion: "Festival",image: '../image/suit5.jfif',description: "Red Mocklayer Solid Kurta",bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000'},
        { id:"fullsuit106",categories: "Fullsuit",name: "Full Suit",dress: 'suit',code: '1014AB',mrp: 'Rs. 4500',price: 2500 ,febric: "cotton",sleeve: "Full Sleeve",color: "Blue",shape: "Straight",pattern: "Printed",care: "Hand Wash",occesion: "Festival",image: '../image/suit6.jfif',description: "Blue Mocklayer Solid Kurta",bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000' },
        { id:"fullsuit107",categories: "Fullsuit",name: "Full Suit",dress: 'suit',code: '1015AB',mrp: 'Rs. 6500',price: 2600 ,febric: "cotton",sleeve: "Full Sleeve",color: "Black",shape: "Straight",pattern: "Printed",care: "Hand Wash",occesion: "Festiva",image: '../image/suit7.jfif ',description: "Blue Mocklayer Solid Kurta", bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000'  },
        { id:"fullsuit108",categories: "Fullsuit",name: "Full Suit",dress: 'suit',code: '1016AB',mrp: 'Rs. 3500',price: 2700 ,febric: "cotton",sleeve: "Full Sleeve",color: "Blue",shape: "Straight",pattern: "Printed",care: "Hand Wash",occesion: "Festival",image: '../image/suit8.jfif',description: "Blue Mocklayer Solid Kurta", bankoffer: 'Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000'},
    
    
    
        {id: "topwear101", categories: "Topwear", name: "Flared Top ", price: 3000 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/tp11.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "topwear102", categories: "Topwear", name: "Flared Top ", price: 3000 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/tp12.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "topwear103", categories: "Topwear", name: "Flared Top ", price: 3000 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/tp13.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "topwear104", categories: "Topwear", name: "Flared Top ", price: 3000 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/tp14.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "topwear105", categories: "Topwear", name: "Flared Top ", price: 3000 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/tp5.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "topwear106", categories: "Topwear", name: "Flared Top ", price: 3000 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/tp6.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "topwear107", categories: "Topwear", name: "Flared Top ", price: 3000 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/tp7.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "topwear108", categories: "Topwear", name: "Flared Top ", price: 3000 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/tp8.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
    
    
        {id: "bottomwear101", categories: "Bottomwear", name: "Bottom Wear", price: 3999 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/bt1.jfif", description: " 'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "bottomwear102", categories: "Bottomwear", name: "Bottom Wear", price: 3999 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/bt2.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "bottomwear103", categories: "Bottomwear", name: "Bottom Wear", price: 3999 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/bt3.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "bottomwear104", categories: "Bottomwear", name: "Bottom Wear", price: 3999 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/bt4.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "bottomwear105", categories: "Bottomwear", name: "Bottom Wear", price: 3999 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/bt5.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "bottomwear106", categories: "Bottomwear", name: "Bottom Wear", price: 3999 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/bt6.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "bottomwear107", categories: "Bottomwear", name: "Bottom Wear", price: 3999 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/bt7.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" },
        {id: "bottomwear108", categories: "Bottomwear", name: "Bottom Wear", price: 3999 , febric: "cotton", sleeve: "Full Sleeve", color: "Blue", shape: "Straight", pattern: "Printed", care: "Hand Wash", occesion: "Festival", image: "../image/bt8.jfif", description: "'ASIAN Men's Rider-01 Phylon Sports,Running,Walking Shoes", bankoffer: "Bank Offer (8): 10% Instant Discount up to INR 1500 on RBL Credit Card Non-EMI Transactions. Minimum purchase of INR 5000" }
        
      ])
 

